version: "3.8"

services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunkie
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_PASSWORD=P@4ssw0rd   # must be 8+ chars, uppercase, lowercase, number, symbol
      - SPLUNK_HEC_TOKEN=ca8b30f6-6fca-4f34-90ad-ef79dc6599cf
      - SPLUNK_ENABLE_HEC=true
      - SPLUNK_HEC_PORT=8088
      - SPLUNK_HEC_SSL=false
    ports:
      - "8000:8000"   # Splunk Web
      - "8088:8088"   # HEC (HTTP Event Collector)
      - "9997:9997"   # Indexing port
      - "8089:8089"   # Splunkd management port
    volumes:
      - splunk_etc:/opt/splunk/etc
      - splunk_var:/opt/splunk/var
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"   # Portainer UI
      - "9443:9443"   # Portainer HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

volumes:
  splunk_etc:
  splunk_var:
  portainer_data:
